### ISSUE TITLE
install express, handlebars, express validation, sqlite3, @handlebars/allow-prototype-access

### ISSUE THREAD

**Issue by saleem2007** [saleem2007/swe-inventory-app-starter#1]
- [x] add start node server.js in package.json

**Comment by LindaEng** [comment]
Nice ticket! Liked how specific you were with the technology dependencies. One constructive feedback I'd give is to specify on the top of the ticket what category it might belong to. For example: DEPENDENCIES: --- -- -- -- x,y,z or BACKEND: (models)
