### ISSUE TITLE
FeedBack

### ISSUE THREAD

**Issue by LindaEng** [saleem2007/swe-inventory-app-starter#9]
I'm very impressed with the style of organization your team used to separate the tickets by tiers. Very clever and very thought out. This task board shows me that your team has excellent harmony and respect between each member. In addition, your board clearly defines your goals by their descriptions. 

One piece of constructive advice is that I would add a title to each card.

BACKEND - (models)
   - [ ] items model 
   - ...//etc

Bravo bravo!

**Comment by saleem2007** [comment]
Ok thank you so much Linda for your great advice, we will get them done.
